---
driver:
  name: ec2
  require_chef_omnibus: 12.17.44
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.large
  interface: public
  tags:
    Env: public
    Type: test

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  run_list:
  - recipe[apt]

platforms:
- name: ubuntu-14.04
  driver:
    tags:
      Name: default-et-nginx-ubuntu-1404
- name: ubuntu-16.04
  driver:
    tags:
      Name: default-et-nginx-ubuntu-1604

suites:
  - name: default
    run_list:
      - recipe[et_nginx::default]
    attributes:
      nginx:
        log_dir: /tmp/nginx_log
  - name: modules
    run_list:
      - recipe[et_nginx::default]
    attributes:
      nginx:
        socketproxy:
          apps:
            test-app: {}
        modules:
        - module_http_geoip
        - module_http_gzip_static
        - module_http_realip
        - module_socketproxy
