driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
        - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[et_nginx::default]
  - name: modules
    run_list:
      - recipe[et_nginx::default]
    attributes:
      nginx:
        socketproxy:
          apps:
            test-app: {}
        modules:
        - module_http_geoip
        - module_http_gzip_static
        - module_http_realip
        - module_naxsi
        - module_upload_progress
        - module_socketproxy
