---
driver_config:
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITAL_OCEAN_API_KEY'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: amazon-ubuntu-1404
  driver_plugin: ec2
  driver_config:
    image_id: ami-44e9752c
    username: ubuntu
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
    interface: public
    flavor_id: c3.large
    security_group_ids: ['ci-testing']
  run_list:
  - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[et_nginx::default]
    attributes:
      nginx:
        log_dir: /tmp/nginx_log
  - name: source
    run_list:
      - recipe[et_nginx::default]
    attributes:
      nginx:
        install_method: source
  - name: upstream_repo
    run_list:
      - recipe[et_nginx::repo]
      - recipe[et_nginx::default]
    attributes:
      nginx:
        repo_source: nginx
  - name: modules
    run_list:
      - recipe[et_nginx::source]
    attributes:
      nginx:
        source:
          modules:
            - et_nginx::headers_more_module
            - et_nginx::http_auth_request_module
            - et_nginx::http_echo_module
            - et_nginx::http_geoip_module
            - et_nginx::http_gzip_static_module
            - et_nginx::http_realip_module
            - et_nginx::http_spdy_module
            - et_nginx::http_ssl_module
            - et_nginx::http_stub_status_module
            - et_nginx::naxsi_module
            - et_nginx::ngx_devel_module
            - et_nginx::ngx_lua_module
            - et_nginx::openssl_source
            - et_nginx::upload_progress_module
