---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>
  instance_type: c3.large
  security_group_ids: ['ci-testing']
  interface: public

transport:
  username: ubuntu
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: amazon-ubuntu-1404
  driver:
    image_id: ami-bbef47d0
  run_list:
  - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[et_nginx::default]
    attributes:
      nginx:
        log_dir: /tmp/nginx_log
  - name: upstream_repo
    run_list:
      - recipe[et_nginx::repo]
      - recipe[et_nginx::default]
    attributes:
      nginx:
        repo_source: nginx
  - name: modules
    run_list:
      - recipe[et_nginx::default]
    attributes:
      nginx:
        modules:
        - et_nginx::module_http_geoip
        - et_nginx::module_http_gzip_static
        - et_nginx::module_http_realip
        - et_nginx::module_naxsi
        - et_nginx::module_upload_progress
