driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.10
  - name: centos-6.5
  - name: ubuntu-10.04
    run_list:
        - recipe[apt]
  - name: ubuntu-12.04
    run_list:
        - recipe[apt]
  - name: ubuntu-14.04
    run_list:
        - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[et_nginx::default]
  - name: source
    run_list:
      - recipe[et_nginx::default]
    attributes:
      nginx:
        install_method: source
  - name: upstream_repo
    run_list:
      - recipe[et_nginx::repo]
      - recipe[et_nginx::default]
    attributes:
      nginx:
        repo_source: nginx
  - name: modules
    run_list:
      - recipe[et_nginx::source]
    attributes:
      nginx:
        modules:
          - et_nginx::module_http_geoip
          - et_nginx::module_http_gzip_static
          - et_nginx::module_http_realip
          - et_nginx::module_naxsi
          - et_nginx::module_upload_progress
