driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[et_nginx::default]
  - name: source
    run_list:
      - recipe[et_nginx::default]
    attributes:
      nginx:
        install_method: source
  - name: upstream_repo
    run_list:
      - recipe[et_nginx::repo]
      - recipe[et_nginx::default]
    attributes:
      nginx:
        repo_source: nginx
  - name: modules
    run_list:
      - recipe[et_nginx::source]
    attributes:
      nginx:
        source:
          modules:
            - et_nginx::headers_more_module
            - et_nginx::http_auth_request_module
            - et_nginx::http_echo_module
            - et_nginx::http_geoip_module
            - et_nginx::http_gzip_static_module
            - et_nginx::http_realip_module
            - et_nginx::http_spdy_module
            - et_nginx::http_ssl_module
            - et_nginx::http_stub_status_module
            - et_nginx::naxsi_module
            - et_nginx::ngx_devel_module
            - et_nginx::ngx_lua_module
            - et_nginx::openssl_source
            - et_nginx::upload_progress_module
